
spring: 
  profiles:
    active:
    - dev
    
    
---


server:
  port: 9527

spring:
  profiles: zuul
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  ignored-services: microservicecloud-dept    # 映射之前的 url 无法在生效, ignored: 忽略    忽略多个: *
  prefix: /atguigu  # 设置统一公共前缀  之后http://myzuul.com:9527/atguigu/mydept/dept/get/1
  routes:                               # 映射之前 http://myzuul.com:9527/microservicecloud-dept/dept/get/2
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**             # 映射之后 http://myzuul.com:9527/mydept/dept/get/1
  

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

