spring: 
  profiles: 
    active: 
    - dev
    
    
---


server:
  port: 7001
  
spring: 
  profiles: 7001
  application:
    name: microservicecloud-eureka-cluster-config
 
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #单机版 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

    #server:
    #enable-self-preservation: false    # 禁用自我保护


---


server:
  port: 7002
  
spring: 
  profiles: 7002
  application:
    name: microservicecloud-eureka-cluster-config  

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #单机版 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
  #server:
    #enable-self-preservation: false    # 禁用自我保护


---

server:
  port: 7003


spring: 
  profiles: 7003
  application:
    name: microservicecloud-eureka-cluster-config
    
eureka:
  instance:
    hostname: eureka7003.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。

    #server:
    #enable-self-preservation: false    # 禁用自我保护


